"""Hypothesis review endpoints — candidate lifecycle management.

Every hypothesis generated by an agent starts as "candidate".
A human reviewer must explicitly accept or reject it before it influences
the knowledge base, triggers downstream experiments, or is treated as a
validated research direction.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.hypothesis import Hypothesis
from app.routers.auth import get_current_user
from app.schemas.hypothesis import HypothesisOut, HypothesisReviewRequest

router = APIRouter(tags=["hypotheses"])


@router.get(
    "/projects/{project_id}/hypotheses/candidates",
    response_model=list[HypothesisOut],
)
async def list_candidates(
    project_id: str,
    db: AsyncSession = Depends(get_db),
    _current_user=Depends(get_current_user),
):
    """Return all hypotheses awaiting human review for a project."""
    from app.models.experiment import Experiment

    result = await db.execute(
        select(Hypothesis)
        .join(Experiment, Hypothesis.experiment_id == Experiment.id)
        .where(
            Experiment.project_id == uuid.UUID(project_id),
            Hypothesis.review_status.in_(["candidate", "under_review"]),
        )
        .order_by(Hypothesis.created_at.desc())
    )
    return result.scalars().all()


@router.get(
    "/projects/{project_id}/hypotheses",
    response_model=list[HypothesisOut],
)
async def list_hypotheses(
    project_id: str,
    review_status: str | None = None,
    db: AsyncSession = Depends(get_db),
    _current_user=Depends(get_current_user),
):
    """Return hypotheses for a project, optionally filtered by review_status."""
    from app.models.experiment import Experiment

    q = (
        select(Hypothesis)
        .join(Experiment, Hypothesis.experiment_id == Experiment.id)
        .where(Experiment.project_id == uuid.UUID(project_id))
        .order_by(Hypothesis.created_at.desc())
    )
    if review_status:
        q = q.where(Hypothesis.review_status == review_status)

    result = await db.execute(q)
    return result.scalars().all()


@router.post(
    "/projects/{project_id}/hypotheses/{hypothesis_id}/review",
    response_model=HypothesisOut,
)
async def review_hypothesis(
    project_id: str,
    hypothesis_id: str,
    body: HypothesisReviewRequest,
    db: AsyncSession = Depends(get_db),
    _current_user=Depends(get_current_user),
):
    """Accept or reject a candidate hypothesis.

    Accepted hypotheses may be stored in the knowledge base and used to
    inform future retrieval. Rejected hypotheses are retained for audit
    but excluded from downstream reasoning.
    """
    if body.decision not in ("accepted", "rejected"):
        raise HTTPException(status_code=422, detail="decision must be 'accepted' or 'rejected'")

    result = await db.execute(
        select(Hypothesis).where(Hypothesis.id == uuid.UUID(hypothesis_id))
    )
    h = result.scalar_one_or_none()
    if h is None:
        raise HTTPException(status_code=404, detail="Hypothesis not found")

    h.review_status = body.decision
    h.review_notes = body.notes
    h.reviewed_at = datetime.now(timezone.utc)

    if body.decision == "accepted":
        await _store_in_knowledge_base(h, project_id)

    await db.commit()
    await db.refresh(h)
    return h


@router.post(
    "/projects/{project_id}/hypotheses/{hypothesis_id}/mark-reviewing",
    response_model=HypothesisOut,
)
async def mark_under_review(
    project_id: str,
    hypothesis_id: str,
    db: AsyncSession = Depends(get_db),
    _current_user=Depends(get_current_user),
):
    """Mark a candidate as 'under_review' to signal active evaluation."""
    result = await db.execute(
        select(Hypothesis).where(Hypothesis.id == uuid.UUID(hypothesis_id))
    )
    h = result.scalar_one_or_none()
    if h is None:
        raise HTTPException(status_code=404, detail="Hypothesis not found")

    if h.review_status == "candidate":
        h.review_status = "under_review"
        await db.commit()
        await db.refresh(h)
    return h


async def _store_in_knowledge_base(h: Hypothesis, project_id: str) -> None:
    """On acceptance, index hypothesis text into the knowledge base for future retrieval."""
    try:
        from memory.knowledge_memory import KnowledgeEntry, store_knowledge
        import uuid as _uuid

        entry = KnowledgeEntry(
            entry_id=str(_uuid.uuid4()),
            text=f"Accepted hypothesis: {h.hypothesis_text}",
            source_paper_id=str(h.id),
            project_id=project_id,
            kind="accepted_hypothesis",
        )
        store_knowledge([entry])
    except Exception:
        pass
