"""Human checkpoint primitives for the research workflow.

Checkpoints enforce scientific rigor by pausing the auto-loop at decision
points that require human judgement:

  1. Hypothesis acceptance  — before a generated hypothesis is stored in the
                              knowledge base and treated as a valid direction
  2. Workflow modification  — before changing core pipeline configuration
  3. Code generation        — before research-engineering artifacts are merged

A checkpoint does NOT prevent the loop from generating candidates; it only
prevents those candidates from propagating downstream until reviewed.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class CheckpointKind(str, Enum):
    HYPOTHESIS_REVIEW = "hypothesis_review"
    WORKFLOW_CHANGE   = "workflow_change"
    CODE_GENERATION   = "code_generation"


class CheckpointStatus(str, Enum):
    PENDING   = "pending"    # awaiting human decision
    APPROVED  = "approved"   # human approved; loop may continue
    REJECTED  = "rejected"   # human rejected; loop should revise
    BYPASSED  = "bypassed"   # explicitly skipped (simulation / test mode only)


@dataclass
class HumanCheckpoint:
    kind: CheckpointKind
    status: CheckpointStatus = CheckpointStatus.PENDING
    reason: str = ""           # why this checkpoint was created
    notes: str = ""            # reviewer notes (set on approval/rejection)
    metadata: dict = field(default_factory=dict)

    @property
    def is_blocking(self) -> bool:
        return self.status == CheckpointStatus.PENDING

    @property
    def approved(self) -> bool:
        return self.status == CheckpointStatus.APPROVED

    @property
    def rejected(self) -> bool:
        return self.status == CheckpointStatus.REJECTED


def hypothesis_checkpoint(hypothesis_id: str, agent_name: str) -> HumanCheckpoint:
    """Create a standard hypothesis-review checkpoint."""
    return HumanCheckpoint(
        kind=CheckpointKind.HYPOTHESIS_REVIEW,
        reason=f"Hypothesis generated by {agent_name} requires human review before acceptance.",
        metadata={"hypothesis_id": hypothesis_id, "agent_name": agent_name},
    )


def requires_review(state: dict) -> bool:
    """Return True when the current state has a blocking checkpoint."""
    cp = state.get("checkpoint")
    return isinstance(cp, dict) and cp.get("status") == CheckpointStatus.PENDING
